import type {
  ActivityItem,
  ComplianceRecord,
  Consignment,
  Customer,
  DocumentRecord,
  GeneralFreightJob,
  IntegrationSetting,
  Lead,
  ProjectFreightJob,
  Supplier,
} from "./types";

export const customers: Customer[] = [
  {
    id: "cust-1",
    companyName: "ABC Construction",
    contactPerson: "James Mitchell",
    phone: "02 9123 4567",
    email: "james@abcconstruction.com.au",
    address: "45 George St, Sydney NSW 2000",
    notes: "Major project freight client. Prefers email communication.",
    xeroContactRef: "XERO-CUST-001",
  },
  {
    id: "cust-2",
    companyName: "BuildRight Pty Ltd",
    contactPerson: "Sarah Chen",
    phone: "02 8234 5678",
    email: "sarah@buildright.com.au",
    address: "12 Industrial Ave, Parramatta NSW 2150",
    notes: "Regular general freight bookings via Transvirtual.",
    xeroContactRef: "XERO-CUST-002",
  },
  {
    id: "cust-3",
    companyName: "Sydney Developments",
    contactPerson: "Michael Torres",
    phone: "02 9345 6789",
    email: "michael@sydneydev.com.au",
    address: "88 Harbour Rd, North Sydney NSW 2060",
    notes: "High-value project freight. Requires compliance docs on all suppliers.",
    xeroContactRef: "XERO-CUST-003",
  },
  {
    id: "cust-4",
    companyName: "Metro Projects",
    contactPerson: "Emma Wilson",
    phone: "02 8456 7890",
    email: "emma@metroprojects.com.au",
    address: "200 Collins St, Melbourne VIC 3000",
    notes: "Melbourne-based. Cross-state project freight.",
    xeroContactRef: "XERO-CUST-004",
  },
  {
    id: "cust-5",
    companyName: "Harbour Constructions",
    contactPerson: "David Park",
    phone: "02 9567 8901",
    email: "david@harbourconstructions.com.au",
    address: "5 Wharf Rd, Port Botany NSW 2036",
    notes: "Port-related logistics. Heavy machinery transport.",
    xeroContactRef: "XERO-CUST-005",
  },
];

export const suppliers: Supplier[] = [
  {
    id: "sup-1",
    name: "Coastal Transport",
    contactPerson: "Peter Walsh",
    phone: "02 9111 2233",
    email: "peter@coastaltransport.com.au",
    serviceType: "Project Freight",
    relatedSystem: "Internal",
    notes: "Primary project freight carrier for NSW.",
    complianceStatus: "Valid",
  },
  {
    id: "sup-2",
    name: "Quick Logistics",
    contactPerson: "Lisa Nguyen",
    phone: "02 9222 3344",
    email: "lisa@quicklogistics.com.au",
    serviceType: "General Freight",
    relatedSystem: "Transvirtual",
    notes: "Transvirtual integration active.",
    complianceStatus: "Expiring Soon",
  },
  {
    id: "sup-3",
    name: "Fast Freight",
    contactPerson: "Tom Bradley",
    phone: "02 9333 4455",
    email: "tom@fastfreight.com.au",
    serviceType: "General Freight",
    relatedSystem: "Transmate",
    notes: "Transmate TMS integration.",
    complianceStatus: "Valid",
  },
  {
    id: "sup-4",
    name: "Metro Haulage",
    contactPerson: "Karen O'Brien",
    phone: "03 9444 5566",
    email: "karen@metrohaulage.com.au",
    serviceType: "Project Freight",
    relatedSystem: "Internal",
    notes: "Melbourne project freight specialist.",
    complianceStatus: "Valid",
  },
  {
    id: "sup-5",
    name: "Internet Courier Services",
    contactPerson: "Ryan Cooper",
    phone: "02 9555 6677",
    email: "ryan@internetcourier.com.au",
    serviceType: "General Freight",
    relatedSystem: "Internet Courier",
    notes: "Internet Courier platform integration.",
    complianceStatus: "Expired",
  },
];

export const projectFreightJobs: ProjectFreightJob[] = [
  {
    id: "pf-1",
    jobNumber: "PF-2024-1048",
    customerId: "cust-1",
    customerName: "ABC Construction",
    contactPerson: "James Mitchell",
    senderName: "ABC Construction — Sydney Yard",
    senderAddress: "45 George St, Sydney NSW 2000",
    receiverName: "ABC Construction — North Sydney Site",
    receiverAddress: "120 Pacific Hwy, North Sydney NSW 2060",
    pickupDetails: "45 George St, Sydney NSW 2000 — Site office, contact James",
    deliveryDetails: "120 Pacific Hwy, North Sydney NSW 2060 — Loading dock B",
    jobDescription: "Steel beam transport — 3 oversized loads for tower construction",
    status: "In Progress",
    dueDate: "2026-07-15",
    assignedSupplierId: "sup-1",
    assignedSupplierName: "Coastal Transport",
    internalNotes: "Permit required for oversize. Supplier confirmed escort vehicle.",
    xeroContactRef: "XERO-CUST-001",
    xeroInvoiceRef: "INV-2024-0892",
    paymentStatusRef: "Pending — awaiting client sign-off",
    proofOfDelivery: "",
    tasks: [
      {
        id: "task-1",
        taskName: "Obtain oversize permit",
        status: "Completed",
        dueDate: "2026-06-20",
        assignedPerson: "Ryan",
        notes: "Permit approved by RMS",
        completed: true,
      },
      {
        id: "task-2",
        taskName: "Confirm escort vehicle",
        status: "In Progress",
        dueDate: "2026-07-01",
        assignedPerson: "Ryan",
        notes: "Coastal Transport arranging",
        completed: false,
      },
      {
        id: "task-3",
        taskName: "Client site access confirmation",
        status: "Pending",
        dueDate: "2026-07-10",
        assignedPerson: "Ryan",
        notes: "Awaiting response from James Mitchell",
        completed: false,
      },
    ],
  },
  {
    id: "pf-2",
    jobNumber: "PF-2024-1052",
    customerId: "cust-3",
    customerName: "Sydney Developments",
    contactPerson: "Michael Torres",
    senderName: "Sydney Developments — North Sydney",
    senderAddress: "88 Harbour Rd, North Sydney NSW 2060",
    receiverName: "Barangaroo Project Site",
    receiverAddress: "15 Barangaroo Ave, Sydney NSW 2000",
    pickupDetails: "88 Harbour Rd, North Sydney NSW 2060",
    deliveryDetails: "15 Barangaroo Ave, Sydney NSW 2000",
    jobDescription: "Crane components — 2 loads, fragile handling required",
    status: "Waiting on Supplier",
    dueDate: "2026-07-22",
    assignedSupplierId: "sup-4",
    assignedSupplierName: "Metro Haulage",
    internalNotes: "Supplier delayed — awaiting crane availability confirmation.",
    xeroContactRef: "XERO-CUST-003",
    xeroInvoiceRef: "INV-2024-0901",
    paymentStatusRef: "Not invoiced",
    proofOfDelivery: "",
    tasks: [
      {
        id: "task-4",
        taskName: "Supplier availability check",
        status: "In Progress",
        dueDate: "2026-06-28",
        assignedPerson: "Ryan",
        notes: "Metro Haulage checking fleet",
        completed: false,
      },
    ],
  },
  {
    id: "pf-3",
    jobNumber: "PF-2024-1055",
    customerId: "cust-5",
    customerName: "Harbour Constructions",
    contactPerson: "David Park",
    senderName: "Harbour Constructions — Port Botany",
    senderAddress: "5 Wharf Rd, Port Botany NSW 2036",
    receiverName: "Harbour Constructions — North Sydney Depot",
    receiverAddress: "200 Miller St, North Sydney NSW 2060",
    pickupDetails: "5 Wharf Rd, Port Botany NSW 2036",
    deliveryDetails: "200 Miller St, North Sydney NSW 2060",
    jobDescription: "Port equipment relocation — forklift and containers",
    status: "Pending",
    dueDate: "2026-08-01",
    assignedSupplierId: "sup-1",
    assignedSupplierName: "Coastal Transport",
    internalNotes: "New job — quote approved, awaiting scheduling.",
    xeroContactRef: "XERO-CUST-005",
    xeroInvoiceRef: "",
    paymentStatusRef: "Quote stage",
    proofOfDelivery: "",
    tasks: [],
  },
  {
    id: "pf-4",
    jobNumber: "PF-2024-1039",
    customerId: "cust-4",
    customerName: "Metro Projects",
    contactPerson: "Emma Wilson",
    senderName: "Metro Projects — Collins St",
    senderAddress: "200 Collins St, Melbourne VIC 3000",
    receiverName: "Metro Projects — Spencer St Office",
    receiverAddress: "50 Spencer St, Melbourne VIC 3000",
    pickupDetails: "200 Collins St, Melbourne VIC 3000",
    deliveryDetails: "50 Spencer St, Melbourne VIC 3000",
    jobDescription: "Office fit-out materials — palletised goods",
    status: "Completed",
    dueDate: "2026-05-30",
    assignedSupplierId: "sup-4",
    assignedSupplierName: "Metro Haulage",
    internalNotes: "Completed without issues. Client satisfied.",
    xeroContactRef: "XERO-CUST-004",
    xeroInvoiceRef: "INV-2024-0875",
    paymentStatusRef: "Paid",
    proofOfDelivery: "PF-2024-1039_POD_signed.pdf",
    tasks: [
      {
        id: "task-5",
        taskName: "Delivery confirmation",
        status: "Completed",
        dueDate: "2026-05-30",
        assignedPerson: "Ryan",
        notes: "Signed delivery receipt received",
        completed: true,
      },
    ],
  },
  {
    id: "pf-5",
    jobNumber: "PF-2024-1060",
    customerId: "cust-1",
    customerName: "ABC Construction",
    contactPerson: "James Mitchell",
    senderName: "ABC Construction — Sydney Yard",
    senderAddress: "45 George St, Sydney NSW 2000",
    receiverName: "Surry Hills Development",
    receiverAddress: "78 Crown St, Surry Hills NSW 2010",
    pickupDetails: "45 George St, Sydney NSW 2000",
    deliveryDetails: "78 Crown St, Surry Hills NSW 2010",
    jobDescription: "Concrete panel delivery — 6 panels",
    status: "Draft",
    dueDate: "2026-08-15",
    assignedSupplierId: "",
    assignedSupplierName: "",
    internalNotes: "Draft — awaiting supplier assignment.",
    xeroContactRef: "XERO-CUST-001",
    xeroInvoiceRef: "",
    paymentStatusRef: "Draft",
    proofOfDelivery: "",
    tasks: [],
  },
];

export const generalFreightJobs: GeneralFreightJob[] = [
  {
    id: "gf-1",
    jobNumber: "GF-2024-2081",
    externalSystem: "Transvirtual",
    externalJobId: "TV-88421",
    customerId: "cust-2",
    customerName: "BuildRight Pty Ltd",
    supplierId: "sup-2",
    supplierName: "Quick Logistics",
    senderName: "BuildRight Pty Ltd",
    senderAddress: "12 Industrial Ave, Parramatta NSW 2150",
    receiverName: "Westfield Site Office",
    receiverAddress: "159 Church St, Parramatta NSW 2150",
    receiverSuburb: "Parramatta",
    pickupDetails: "12 Industrial Ave, Parramatta — dock 3",
    deliveryDetails: "159 Church St, Parramatta — rear entrance",
    quantity: "6 pallets",
    weight: "1,240 kg",
    cubic: "8.4 m³",
    notes: "Tail-lift required at delivery.",
    status: "In Transit",
    lastSynced: "2026-06-24T14:30:00",
    syncState: "Synced",
  },
  {
    id: "gf-2",
    jobNumber: "GF-2024-2090",
    externalSystem: "Transmate",
    externalJobId: "TM-55210",
    customerId: "cust-2",
    customerName: "BuildRight Pty Ltd",
    supplierId: "sup-3",
    supplierName: "Fast Freight",
    senderName: "BuildRight Pty Ltd",
    senderAddress: "12 Industrial Ave, Parramatta NSW 2150",
    receiverName: "Newcastle Depot",
    receiverAddress: "24 Hannell St, Wickham NSW 2293",
    receiverSuburb: "Wickham",
    pickupDetails: "12 Industrial Ave, Parramatta",
    deliveryDetails: "24 Hannell St, Wickham — call on arrival",
    quantity: "3 crates",
    weight: "620 kg",
    cubic: "3.1 m³",
    notes: "Fragile — glass panels.",
    status: "Booked",
    lastSynced: "2026-06-23T09:15:00",
    syncState: "Synced",
  },
  {
    id: "gf-3",
    jobNumber: "GF-2024-2095",
    externalSystem: "Internet Courier",
    externalJobId: "IC-33107",
    customerId: "cust-4",
    customerName: "Metro Projects",
    supplierId: "sup-5",
    supplierName: "Internet Courier Services",
    senderName: "Metro Projects",
    senderAddress: "200 Collins St, Melbourne VIC 3000",
    receiverName: "Geelong Warehouse",
    receiverAddress: "5 Gordon Ave, Geelong VIC 3220",
    receiverSuburb: "Geelong",
    pickupDetails: "200 Collins St, Melbourne — loading bay",
    deliveryDetails: "5 Gordon Ave, Geelong",
    quantity: "1 carton",
    weight: "18 kg",
    cubic: "0.2 m³",
    notes: "Express overnight service.",
    status: "Booked",
    lastSynced: "2026-06-22T16:45:00",
    syncState: "Error",
    errorMessage: "Authentication token expired — reconnection required",
  },
  {
    id: "gf-4",
    jobNumber: "GF-2024-2102",
    externalSystem: "Transvirtual",
    externalJobId: "TV-88550",
    customerId: "cust-3",
    customerName: "Sydney Developments",
    supplierId: "sup-2",
    supplierName: "Quick Logistics",
    senderName: "Sydney Developments",
    senderAddress: "88 Harbour Rd, North Sydney NSW 2060",
    receiverName: "Chatswood Site",
    receiverAddress: "12 Help St, Chatswood NSW 2067",
    receiverSuburb: "Chatswood",
    pickupDetails: "88 Harbour Rd, North Sydney",
    deliveryDetails: "12 Help St, Chatswood",
    quantity: "10 pallets",
    weight: "2,100 kg",
    cubic: "14.0 m³",
    notes: "Delivered and signed.",
    status: "Delivered",
    lastSynced: "2026-06-20T11:00:00",
    syncState: "Synced",
  },
  {
    id: "gf-5",
    jobNumber: "GF-2024-2108",
    externalSystem: "Other Supplier System",
    externalJobId: "OSS-9901",
    customerId: "cust-5",
    customerName: "Harbour Constructions",
    supplierId: "sup-1",
    supplierName: "Coastal Transport",
    senderName: "Harbour Constructions",
    senderAddress: "5 Wharf Rd, Port Botany NSW 2036",
    receiverName: "Wollongong Yard",
    receiverAddress: "3 Flinders St, Wollongong NSW 2500",
    receiverSuburb: "Wollongong",
    pickupDetails: "5 Wharf Rd, Port Botany",
    deliveryDetails: "3 Flinders St, Wollongong",
    quantity: "2 containers",
    weight: "4,800 kg",
    cubic: "33.0 m³",
    notes: "Awaiting external ID confirmation.",
    status: "Draft",
    lastSynced: "2026-06-24T08:00:00",
    syncState: "Needs Review",
    errorMessage: "Manual review required — external ID mismatch",
  },
  {
    id: "gf-6",
    jobNumber: "GF-2024-2110",
    externalSystem: "Transmate",
    externalJobId: "TM-55300",
    customerId: "cust-1",
    customerName: "ABC Construction",
    supplierId: "sup-3",
    supplierName: "Fast Freight",
    senderName: "ABC Construction",
    senderAddress: "45 George St, Sydney NSW 2000",
    receiverName: "Penrith Depot",
    receiverAddress: "89 Mulgoa Rd, Penrith NSW 2750",
    receiverSuburb: "Penrith",
    pickupDetails: "45 George St, Sydney",
    deliveryDetails: "89 Mulgoa Rd, Penrith",
    quantity: "4 pallets",
    weight: "980 kg",
    cubic: "6.2 m³",
    notes: "Sync in progress with Transmate.",
    status: "Booked",
    lastSynced: "2026-06-24T10:30:00",
    syncState: "Syncing",
  },
];

export const leads: Lead[] = [
  {
    id: "lead-1",
    companyName: "Pacific Builders",
    contactPerson: "Andrew Clarke",
    phone: "02 9666 7788",
    email: "andrew@pacificbuilders.com.au",
    leadSource: "Website enquiry",
    status: "New",
    notes: "Interested in project freight for new development at Bondi.",
    followUpDate: "2026-06-28",
    freightType: "Project Freight",
  },
  {
    id: "lead-2",
    companyName: "Urban Logistics Co",
    contactPerson: "Nicole Fraser",
    phone: "02 9777 8899",
    email: "nicole@urbanlogistics.com.au",
    leadSource: "Referral",
    status: "Contacted",
    notes: "Looking for general freight integration with Transvirtual.",
    followUpDate: "2026-06-30",
    freightType: "General Freight",
  },
  {
    id: "lead-3",
    companyName: "Greenfield Developments",
    contactPerson: "Chris Hammond",
    phone: "02 9888 9900",
    email: "chris@greenfielddev.com.au",
    leadSource: "Trade show",
    status: "Proposal",
    notes: "Proposal sent for ongoing project freight contract.",
    followUpDate: "2026-07-05",
    freightType: "Project Freight",
  },
  {
    id: "lead-4",
    companyName: "Coastal Warehousing",
    contactPerson: "Amanda Lee",
    phone: "02 9999 0011",
    email: "amanda@coastalwarehousing.com.au",
    leadSource: "Cold call",
    status: "Follow Up",
    notes: "Follow up on general freight rates for palletised goods.",
    followUpDate: "2026-06-27",
    freightType: "General Freight",
  },
  {
    id: "lead-5",
    companyName: "Northern Star Construction",
    contactPerson: "Robert Singh",
    phone: "02 9000 1122",
    email: "robert@northernstar.com.au",
    leadSource: "Website enquiry",
    status: "Won",
    notes: "Converted to customer — first job PF-2024-1048.",
    followUpDate: "2026-06-15",
    freightType: "Project Freight",
  },
];

export const complianceRecords: ComplianceRecord[] = [
  {
    id: "comp-1",
    supplierId: "sup-2",
    supplierName: "Quick Logistics",
    documentType: "Public Liability",
    documentName: "Quick_Logistics_PL_2025.pdf",
    expiryDate: "2026-08-15",
    status: "Expiring Soon",
    notes: "Renewal reminder sent to Lisa Nguyen",
  },
  {
    id: "comp-2",
    supplierId: "sup-5",
    supplierName: "Internet Courier Services",
    documentType: "Insurance",
    documentName: "ICS_Insurance_2024.pdf",
    expiryDate: "2026-03-01",
    status: "Expired",
    notes: "Expired — supplier notified. Jobs on hold until renewed.",
  },
  {
    id: "comp-3",
    supplierId: "sup-1",
    supplierName: "Coastal Transport",
    documentType: "Insurance",
    documentName: "Coastal_Transport_Insurance_2026.pdf",
    expiryDate: "2027-01-15",
    status: "Valid",
    notes: "Annual renewal completed",
  },
  {
    id: "comp-4",
    supplierId: "sup-3",
    supplierName: "Fast Freight",
    documentType: "Licence",
    documentName: "Fast_Freight_Operators_Licence.pdf",
    expiryDate: "2026-12-01",
    status: "Valid",
    notes: "",
  },
  {
    id: "comp-5",
    supplierId: "sup-4",
    supplierName: "Metro Haulage",
    documentType: "Contractor Agreement",
    documentName: "Metro_Haulage_Agreement_2026.pdf",
    expiryDate: "2027-06-30",
    status: "Valid",
    notes: "Signed agreement on file",
  },
  {
    id: "comp-6",
    supplierId: "sup-2",
    supplierName: "Quick Logistics",
    documentType: "Police Check",
    documentName: "",
    expiryDate: "",
    status: "Missing",
    notes: "Police check not yet submitted",
  },
];

export const documents: DocumentRecord[] = [
  {
    id: "doc-1",
    fileName: "PF-2024-1048_Permit.pdf",
    relatedRecord: "PF-2024-1048",
    relatedType: "Project Freight",
    type: "Job Document",
    uploadedBy: "Ryan",
    uploadedDate: "2026-06-20",
    status: "Active",
  },
  {
    id: "doc-2",
    fileName: "Quick_Logistics_PL_2025.pdf",
    relatedRecord: "Quick Logistics",
    relatedType: "Compliance",
    type: "Public Liability",
    uploadedBy: "Ryan",
    uploadedDate: "2025-08-15",
    status: "Expiring Soon",
  },
  {
    id: "doc-3",
    fileName: "ABC_Construction_Contract.pdf",
    relatedRecord: "ABC Construction",
    relatedType: "Customer",
    type: "Customer Document",
    uploadedBy: "Ryan",
    uploadedDate: "2026-01-10",
    status: "Active",
  },
  {
    id: "doc-4",
    fileName: "Coastal_Transport_Insurance_2026.pdf",
    relatedRecord: "Coastal Transport",
    relatedType: "Compliance",
    type: "Insurance",
    uploadedBy: "Ryan",
    uploadedDate: "2026-01-15",
    status: "Active",
  },
  {
    id: "doc-5",
    fileName: "GF-2024-2081_Connote.pdf",
    relatedRecord: "GF-2024-2081",
    relatedType: "General Freight",
    type: "Job Document",
    uploadedBy: "System (Transvirtual)",
    uploadedDate: "2026-06-24",
    status: "Active",
  },
  {
    id: "doc-6",
    fileName: "PF-2024-1039_POD_signed.pdf",
    relatedRecord: "PF-2024-1039",
    relatedType: "Project Freight",
    type: "Proof of Delivery",
    uploadedBy: "Ryan",
    uploadedDate: "2026-05-30",
    status: "Active",
  },
  {
    id: "doc-7",
    fileName: "PF-2024-1039_delivery_signature.png",
    relatedRecord: "PF-2024-1039",
    relatedType: "Project Freight",
    type: "Signature",
    uploadedBy: "Metro Haulage",
    uploadedDate: "2026-05-30",
    status: "Active",
  },
  {
    id: "doc-8",
    fileName: "PF-2024-1039_offload_photo.jpg",
    relatedRecord: "PF-2024-1039",
    relatedType: "Project Freight",
    type: "Delivery Photo",
    uploadedBy: "Metro Haulage",
    uploadedDate: "2026-05-30",
    status: "Active",
  },
  {
    id: "doc-9",
    fileName: "Quick_Logistics_rate_card.pdf",
    relatedRecord: "Quick Logistics",
    relatedType: "Supplier",
    type: "Supplier Document",
    uploadedBy: "Ryan",
    uploadedDate: "2026-02-11",
    status: "Active",
  },
];

export const consignments: Consignment[] = [
  {
    id: "con-1",
    consignmentId: "CON-2024-3310",
    externalSystem: "Transvirtual",
    customerId: "cust-2",
    customerName: "BuildRight Pty Ltd",
    supplierId: "sup-2",
    supplierName: "Quick Logistics",
    senderName: "BuildRight Pty Ltd",
    receiverName: "Westfield Site Office",
    receiverSuburb: "Parramatta",
    quantity: "6 pallets",
    weight: "1,240 kg",
    cubic: "8.4 m³",
    notes: "Tail-lift required at delivery.",
    bookingDate: "2026-06-24",
    status: "In Transit",
    lastSynced: "2026-06-24T14:30:00",
    generalFreightJobId: "gf-1",
    generalFreightJobNumber: "GF-2024-2081",
  },
  {
    id: "con-2",
    consignmentId: "CON-2024-3315",
    externalSystem: "Transmate",
    customerId: "cust-2",
    customerName: "BuildRight Pty Ltd",
    supplierId: "sup-3",
    supplierName: "Fast Freight",
    senderName: "BuildRight Pty Ltd",
    receiverName: "Newcastle Depot",
    receiverSuburb: "Wickham",
    quantity: "3 crates",
    weight: "620 kg",
    cubic: "3.1 m³",
    notes: "Fragile — glass panels.",
    bookingDate: "2026-06-23",
    status: "Booked",
    lastSynced: "2026-06-23T09:15:00",
    generalFreightJobId: "gf-2",
    generalFreightJobNumber: "GF-2024-2090",
  },
  {
    id: "con-3",
    consignmentId: "CON-2024-3320",
    externalSystem: "Internet Courier",
    customerId: "cust-4",
    customerName: "Metro Projects",
    supplierId: "sup-5",
    supplierName: "Internet Courier Services",
    senderName: "Metro Projects",
    receiverName: "Geelong Warehouse",
    receiverSuburb: "Geelong",
    quantity: "1 carton",
    weight: "18 kg",
    cubic: "0.2 m³",
    notes: "Express overnight service.",
    bookingDate: "2026-06-22",
    status: "Error",
    lastSynced: "2026-06-22T16:45:00",
    generalFreightJobId: "gf-3",
    generalFreightJobNumber: "GF-2024-2095",
  },
  {
    id: "con-4",
    consignmentId: "CON-2024-3288",
    externalSystem: "Transvirtual",
    customerId: "cust-3",
    customerName: "Sydney Developments",
    supplierId: "sup-2",
    supplierName: "Quick Logistics",
    senderName: "Sydney Developments",
    receiverName: "Chatswood Site",
    receiverSuburb: "Chatswood",
    quantity: "10 pallets",
    weight: "2,100 kg",
    cubic: "14.0 m³",
    notes: "Delivered and signed.",
    bookingDate: "2026-06-20",
    status: "Delivered",
    lastSynced: "2026-06-20T11:00:00",
    generalFreightJobId: "gf-4",
    generalFreightJobNumber: "GF-2024-2102",
  },
];

export const activities: ActivityItem[] = [
  {
    id: "act-1",
    message: "GF-2024-2081 synced from Transvirtual — status: In Transit",
    timestamp: "2026-06-24T14:30:00",
    type: "sync",
  },
  {
    id: "act-2",
    message: "Permit document uploaded for PF-2024-1048",
    timestamp: "2026-06-20T10:15:00",
    type: "document",
  },
  {
    id: "act-3",
    message: "New lead added: Pacific Builders",
    timestamp: "2026-06-19T09:00:00",
    type: "lead",
  },
  {
    id: "act-4",
    message: "Compliance alert: Quick Logistics PL expiring 15 Aug 2026",
    timestamp: "2026-06-18T08:30:00",
    type: "compliance",
  },
  {
    id: "act-5",
    message: "PF-2024-1039 marked as Completed",
    timestamp: "2026-06-15T16:45:00",
    type: "job",
  },
  {
    id: "act-6",
    message: "GF-2024-2095 sync error — Internet Courier auth failed",
    timestamp: "2026-06-22T16:45:00",
    type: "error",
  },
];

export const integrations: IntegrationSetting[] = [
  {
    id: "int-1",
    name: "Xero",
    status: "Reference",
    description: "Contact + invoice references; draft invoice creation where agreed. Xero stays the source of truth.",
  },
  {
    id: "int-2",
    name: "Transvirtual",
    status: "Primary candidate",
    description: "Targeted Phase 1 API proof-of-concept (subject to API access).",
  },
  {
    id: "int-3",
    name: "Transmate",
    status: "Manual / reference",
    description: "Manual/reference or CSV in Phase 1. Live API a potential bonus if written vendor access is confirmed.",
  },
  {
    id: "int-4",
    name: "Internet Courier",
    status: "Manual / reference",
    description: "Manual/reference or CSV in Phase 1. Live API a potential bonus if written vendor access is confirmed.",
  },
];
